name: <%= File.basename(Dir.pwd) %>

on_project_start:
  - bundle install
  - mkdir -p tmp/puma tmp/uploads tmp/store

windows:
  - dev:
      layout: main-horizontal
      panes:
        -
        - faktory
        - rerun -i 'spec/*' foreman start
        - fswatch nginx.conf | xargs -I {} nginx -s reload
