name: <%= File.basename(Dir.pwd) %>

on_project_start:
  - bundle install
  - mkdir -p tmp/puma tmp/uploads tmp/store

windows:
  - dev:
      layout: main-horizontal
      panes:
        -
        - nginx -p $PWD -c nginx.conf
        - fswatch nginx.conf | xargs -I {} nginx -s reload
        - rerun -- bundle exec puma --config puma.rb
